---

- name: Checking if ansible_distribution_major_version and ansible_distribution are not defined
  fail:
    msg: "Ansible distribution or ansible distribution version are not defined"
  when: ansible_distribution_major_version is not defined or ansible_distribution is not defined

- name: Checking if target server is not CentOS 7
  fail:
    msg: "This role can only be run on CentOS 7 servers"
  when: ansible_distribution != "CentOS" or (ansible_distribution == "CentOS" and ansible_distribution_major_version != "7")

- name: Importing the FileBeats public GPG key into rpm
  rpm_key:
    state: absent
    key: "{{ filebeats_rpm_key }}"
  become: yes
  
- name: Creating a new yum repository file for elastic-beats
  template:
    src: elastic-beats.repo.j2
    dest: "/etc/yum.repos.d/{{ elasticbeats_repo_name }}"
  become: yes
  
- name: Installing filebeat pkg from repo
  yum: 
    name: "{{ filebeat_pkg_name }}"
    state: present
  become: yes

- name: Configure filebeat
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
  become: yes 
  
- name: Configure filebeat-service
  template:
    src: filebeat.service.j2
    dest: "/lib/systemd/system/{{ filebeat_service }}"
  become: yes
  
- name: Reload systemctl
  command: systemctl daemon-reload
  become: yes
  
- name: Logrotate configuration file
  template:
    src: logrotate.filebeat.j2
    dest: /etc/logrotate.d/filebeat
  become: yes  

- name: Restart filebeat
  service:
    name: "{{ filebeat_service_name }}"
    state: restarted 
    enabled: yes
  become: yes
